parameters:
  - name: appEnv
    type: string
  - name: project
    type: string
  - name: tags
    type: string
  - name: dotenvkey
    type: string


stages:
  - stage: RunTestsAndPublishArtifacts
    jobs:
      - job: InstallDependenciesAndRunTests
        steps:
          - task: UseNode@1
            inputs:
              version: "18.17.1"
            displayName: "Install Node.js"
          - script: |
              git clean -ffdx
            displayName: "Clean repository"
          - script: |
              npm install
              npx playwright install
            displayName: "Install dependencies"
          - script: |
              npm run lint
            displayName: "Check code linting"
          - script: |
              npx playwright test src/tests/${{ parameters.project }} -g ${{ parameters.tags }}
            env:
              DOTENV_KEY: ${{ parameters.dotenvkey }}   
              CI: true                        
            displayName: "Execute tests using DOT_ENV KEY"
          - publish: $(System.DefaultWorkingDirectory)/playwright-report
            artifact: 'playwright-report-$(Build.BuildNumber)-$(System.JobAttempt)'
            displayName: "Publish artifacts in the working directory"
            condition: always()
